### ISSUE TITLE
Question regarding obfuscation

### ISSUE THREAD

**Issue by tkirkland** [novice88/jetbra#2]
Is it possible to prevent plugin detection of ja-netfilter?

![image](https://github.com/novice88/jetbra/assets/18052612/06a8a5b2-c20a-4ab6-9593-944d80d71653)

starxg released a 'license facade patcher,' but the repo has since gone.

I appreciate your work!

**Comment by novice88** [comment]
If you are using this project, you will not encounter this problem.

For ja-netfilter, a plugin needs to be developed to prevent the detection of this plugin. Unfortunately, I have no plans to develop a plugin for ja-netfilter.

You can try to remove ja-netfiler by executing the uninstall script and then install this project
