### ISSUE TITLE
key is invalid

### ISSUE THREAD

**Issue by kynightyk** [novice88/jetbra#4]
my idea version is 
![image](https://github.com/novice88/jetbra/assets/50066608/3cec9b4b-b1b9-45a8-88cc-211f9b1d8689)

but activate Restful Fast Request - API Buddy prompt key is invalid
![image](https://github.com/novice88/jetbra/assets/50066608/30674622-f72c-4364-9232-8a348c798361)

**Comment by novice88** [comment]
Can you provide the vm option file that your idea is using and the idea startup logs?

**Comment by kynightyk** [comment]
> Can you provide the vm option file that your idea is using and the idea startup logs?
vm option
![image](https://github.com/novice88/jetbra/assets/50066608/720ff340-a9f9-4f84-b9c7-d3065e89418d)

idea startup logs
[idea.log](https://github.com/novice88/jetbra/files/14059921/idea.log)

**Comment by kynightyk** [comment]
The image above is from folder C:\Users\Public\jetbra\vmoptions
![image](https://github.com/novice88/jetbra/assets/50066608/98889ccb-ff05-4fc3-a1ab-0465d7d0c8ca)


VM option under folder C:\Users\123\AppData\Roaming\JetBrains\IntelliJIdea2023.3 is 
![image](https://github.com/novice88/jetbra/assets/50066608/7799e0cf-3ed2-4caf-8026-6f3d4500f477)

**Comment by novice88** [comment]
You are using ja-netfilter instead of this project, have you configured power.conf correctly?
make sure you add the following configuration to the results section of power.conf
```
EQUAL,552256481678533139637975642367886203758236695483472209227743107098274039115182632876163871002685432662302338668484423414183623828225303129495011678242692842492488816514989676246788248148342413267485195568231641482216898266877438354128287060766631859161479332205725666574464164020522537595703362075565234890263790811265628293553656776925959545054122892468596656349514684518208997243750044021837251938753278807502305685113970717218831835618638457758130244769634525644949374508517044601990948117620105271720428259518909031341417933211526168184737184239634893948475085109420481522243358927998080508613356123692889767778533191484116809048763806053864339307673413329622302838455339868310031694563895311196234390180465202269142275598079255373287732431039254464172062988256518444614496248243200781259934221113710095392103382136300966279867703201614910212881522237167155093128902262921185900884869382176544761664777559104752378158192377647794361684542114437145121112034418220761298224143523298442362011266447239773883726746341810632935875214148521014297762215812293965213101140233155347800537083565331646491142112103328400294630793407149764120146697310714474595556761774911418274155051344410984326483216333907679252415962391346653515408516718,65537,860106576952879101192782278876319243486072481962999610484027161162448933268423045647258145695082284265933019120714643752088997312766689988016808929265129401027490891810902278465065056686129972085119605237470899952751915070244375173428976413406363879128531449407795115913715863867259163957682164040613505040314747660800424242248055421184038777878268502955477482203711835548014501087778959157112423823275878824729132393281517778742463067583320091009916141454657614089600126948087954465055321987012989937065785013284988096504657892738536613208311013047138019418152103262155848541574327484510025594166239784429845180875774012229784878903603491426732347994359380330103328705981064044872334790365894924494923595382470094461546336020961505275530597716457288511366082299255537762891238136381924520749228412559219346777184174219999640906007205260040707839706131662149325151230558316068068139406816080119906833578907759960298749494098180107991752250725928647349597506532778539709852254478061194098069801549845163358315116260915270480057699929968468068015735162890213859113563672040630687357054902747438421559817252127187138838514773245413540030800888215961904267348727206110582505606182944023582459006406137831940959195566364811905585377246353->31872219281407242025505148642475109331663948030010491344733687844358944945421064967310388547820970408352359213697487269225694990179009814674781374751323403257628081559561462351695605167675284372388551941279783515209238245831229026662363729380633136520288327292047232179909791526492877475417113579821717193807584807644097527647305469671333646868883650312280989663788656507661713409911267085806708237966730821529702498972114194166091819277582149433578383639532136271637219758962252614390071122773223025154710411681628917523557526099053858210363406122853294409830276270946292893988830514538950951686480580886602618927728470029090747400687617046511462665469446846624685614084264191213318074804549715573780408305977947238915527798680393538207482620648181504876534152430149355791756374642327623133843473947861771150672096834149014464956451480803326284417202116346454345929350148770746553056995922154382822307758515805142704373984019252210715650875853634697920708113806880196144197384637328982263167395073688501517286678083973976140696077590122053014085412828620051470085033364773099146103525313018873319293728800442101520384088109603555959893639842091339193891977395427305674935962998394201154475636326880291448367598036283623703166979
```

**Comment by kynightyk** [comment]
> You are using ja-netfilter instead of this project, have you configured power.conf correctly? make sure you add the following configuration to the results section of power.conf
> 
> ```
> EQUAL,552256481678533139637975642367886203758236695483472209227743107098274039115182632876163871002685432662302338668484423414183623828225303129495011678242692842492488816514989676246788248148342413267485195568231641482216898266877438354128287060766631859161479332205725666574464164020522537595703362075565234890263790811265628293553656776925959545054122892468596656349514684518208997243750044021837251938753278807502305685113970717218831835618638457758130244769634525644949374508517044601990948117620105271720428259518909031341417933211526168184737184239634893948475085109420481522243358927998080508613356123692889767778533191484116809048763806053864339307673413329622302838455339868310031694563895311196234390180465202269142275598079255373287732431039254464172062988256518444614496248243200781259934221113710095392103382136300966279867703201614910212881522237167155093128902262921185900884869382176544761664777559104752378158192377647794361684542114437145121112034418220761298224143523298442362011266447239773883726746341810632935875214148521014297762215812293965213101140233155347800537083565331646491142112103328400294630793407149764120146697310714474595556761774911418274155051344410984326483216333907679252415962391346653515408516718,65537,860106576952879101192782278876319243486072481962999610484027161162448933268423045647258145695082284265933019120714643752088997312766689988016808929265129401027490891810902278465065056686129972085119605237470899952751915070244375173428976413406363879128531449407795115913715863867259163957682164040613505040314747660800424242248055421184038777878268502955477482203711835548014501087778959157112423823275878824729132393281517778742463067583320091009916141454657614089600126948087954465055321987012989937065785013284988096504657892738536613208311013047138019418152103262155848541574327484510025594166239784429845180875774012229784878903603491426732347994359380330103328705981064044872334790365894924494923595382470094461546336020961505275530597716457288511366082299255537762891238136381924520749228412559219346777184174219999640906007205260040707839706131662149325151230558316068068139406816080119906833578907759960298749494098180107991752250725928647349597506532778539709852254478061194098069801549845163358315116260915270480057699929968468068015735162890213859113563672040630687357054902747438421559817252127187138838514773245413540030800888215961904267348727206110582505606182944023582459006406137831940959195566364811905585377246353->31872219281407242025505148642475109331663948030010491344733687844358944945421064967310388547820970408352359213697487269225694990179009814674781374751323403257628081559561462351695605167675284372388551941279783515209238245831229026662363729380633136520288327292047232179909791526492877475417113579821717193807584807644097527647305469671333646868883650312280989663788656507661713409911267085806708237966730821529702498972114194166091819277582149433578383639532136271637219758962252614390071122773223025154710411681628917523557526099053858210363406122853294409830276270946292893988830514538950951686480580886602618927728470029090747400687617046511462665469446846624685614084264191213318074804549715573780408305977947238915527798680393538207482620648181504876534152430149355791756374642327623133843473947861771150672096834149014464956451480803326284417202116346454345929350148770746553056995922154382822307758515805142704373984019252210715650875853634697920708113806880196144197384637328982263167395073688501517286678083973976140696077590122053014085412828620051470085033364773099146103525313018873319293728800442101520384088109603555959893639842091339193891977395427305674935962998394201154475636326880291448367598036283623703166979
> ```

This is what I added, but it still doesn't work

![Uploading 企业微信截图_20240126142544.png…]()

**Comment by kynightyk** [comment]
![企业微信截图_20240126142544](https://github.com/novice88/jetbra/assets/50066608/406e0b01-2a16-44af-8f40-4fa2a64d553d)

**Comment by novice88** [comment]
> ![企业微信截图_20240126142544](https://private-user-images.githubusercontent.com/50066608/299897176-406e0b01-2a16-44af-8f40-4fa2a64d553d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNTEzNTEsIm5iZiI6MTcwNjI1MTA1MSwicGF0aCI6Ii81MDA2NjYwOC8yOTk4OTcxNzYtNDA2ZTBiMDEtMmExNi00NGFmLThmNDAtNGZhMmE2NGQ1NTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA2MzczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxM2EwMjY5MDA3ZDcxZDllNzhhMTFkYjk5YmM1ZDI2NjJjMDBiZTBhYWEzZTM5ZWY3OGZhNTJlNDcxZTAwZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dvVlTK_DYEh18lpprvtvr8DxdOU7EQV7tj3ltGKDQgk)

You must add the configuration to the result section！！！

**Comment by kynightyk** [comment]
> > ![企业微信截图_20240126142544](https://private-user-images.githubusercontent.com/50066608/299897176-406e0b01-2a16-44af-8f40-4fa2a64d553d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNTEzNTEsIm5iZiI6MTcwNjI1MTA1MSwicGF0aCI6Ii81MDA2NjYwOC8yOTk4OTcxNzYtNDA2ZTBiMDEtMmExNi00NGFmLThmNDAtNGZhMmE2NGQ1NTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA2MzczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxM2EwMjY5MDA3ZDcxZDllNzhhMTFkYjk5YmM1ZDI2NjJjMDBiZTBhYWEzZTM5ZWY3OGZhNTJlNDcxZTAwZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dvVlTK_DYEh18lpprvtvr8DxdOU7EQV7tj3ltGKDQgk)
> 
> You must add the configuration to the result section！！！ not Args

Thank you very much

**Comment by kynightyk** [comment]
After activation, there is a problem as shown in the figure below, and the button for sending requests is grayed out. Can you help solve this problem?

![image](https://github.com/novice88/jetbra/assets/50066608/89b004b0-49f5-47ab-a2d9-21da74f1e9d4)
![image](https://github.com/novice88/jetbra/assets/50066608/6987c5cb-25bb-44e8-ab54-68cbfbb1264c)

**Comment by novice88** [comment]
In theory, you shouldn't be asking me to solve this problem because you're using ja-netfilter, but I happen to know how to fix it, and the reason for the problem is that the plugin uploads the activation code to the server for detection, so it's enough to block the server address by adding the following configuration to your `url.conf`.

```
KEYWORD,116.62.33.138
```

**Comment by kynightyk** [comment]
> In theory, you shouldn't be asking me to solve this problem because you're using ja-netfilter, but I happen to know how to fix it, and the reason for the problem is that the plugin uploads the activation code to the server for detection, so it's enough to block the server address by adding the following configuration to your `url.conf`.
> 
> ```
> KEYWORD,116.62.33.138
> ```

Please forgive my excessive demands. Anyway, thank you for your selfless help
