### ISSUE TITLE
Error with "Invalid Key" in PyCharm Professional

### ISSUE THREAD

**Issue by Hiallthejetbrains** [novice88/jetbra#5]
I am attempting to activate a Jetbrains PyCharm Professional version with the key copied from the website linked in the description. I am using PyCharm Build #PY-241.8102.133 which is in EAP, with the vm options being the following:
`Xms128m
-Xmx1024m
-XX:ReservedCodeCacheSize=512m
-XX:+IgnoreUnrecognizedVMOptions
-XX:+UseG1GC
-XX:SoftRefLRUPolicyMSPerMB=50
-XX:CICompilerCount=2
-XX:+HeapDumpOnOutOfMemoryError
-XX:-OmitStackTraceInFastThrow
-ea
-Dsun.io.useCanonCaches=false
-Djdk.http.auth.tunneling.disabledSchemes=""
-Djdk.attach.allowAttachSelf=true
-Djdk.module.illegalAccess.silent=true
-Dkotlinx.coroutines.debug=off
-XX:ErrorFile=$USER_HOME/java_error_in_idea_%p.log
-XX:HeapDumpPath=$USER_HOME/java_error_in_idea.hprof

--add-opens=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED
--add-opens=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED

-javaagent:/Users/****/jetbra/ja-netfilter.jar=jetbrains`
These were generated by the automatic install script packaged with the repository. Any suggestions would be appreciated. (Probably going to be some dumb mistake on my part, but I have been unable to figure out the problem.)

**Comment by novice88** [comment]
you can refer #4

**Comment by Hiallthejetbrains** [comment]
I assumed that given the fact that I had used the automated installer I would be fine. What steps in #4 should I follow to fix this issue?

**Comment by Hiallthejetbrains** [comment]
Actually, I just realized I may have an out-dated version, and therefore downloaded the newest version, but I am getting the error `jetbra-agent.jar not found` when running the install.sh file in jetbra/script. How do I fix my new error?

**Comment by novice88** [comment]
From the vm options file, it looks like you're using ja-netfilter.

**Comment by novice88** [comment]
I suggest that you run the ja-netfilter uninstall script as well as the jetbra uninstall script, then remove both completely, reboot your computer, and install jetbra again.

**Comment by Hiallthejetbrains** [comment]
How do I uninstall ja-netfilter? I only see one uninstall.sh file in jetbra and I had already ran that.

**Comment by novice88** [comment]
> How do I uninstall ja-netfilter? I only see one uninstall.sh file in jetbra and I had already ran that. Do I just delete the folder I downloaded?

![image](https://github.com/novice88/jetbra/assets/76272583/54470469-cd24-431f-a628-7b7d82f3fb6b)

This is where your ja-netfilter is installed.

**Comment by Hiallthejetbrains** [comment]
So me replacing the /Users/****/jetbra with the new release after uninstalling the old one is what I have to do?

**Comment by novice88** [comment]
This project is not a new version of ja-netfilter, after you make sure to uninstall ja-netfilter completely, execute the install script of this project, then reboot your computer and check if the environment variable PYCHARM_VM_OPTIONS is correct.

**Comment by Hiallthejetbrains** [comment]
Is the PYCHARM_VM_OPTIONS this file?
<img width="114" alt="File" src="https://github.com/novice88/jetbra/assets/157857426/f8d6a769-ea2d-4544-8cda-1d611c52345d">

**Comment by novice88** [comment]
yes,show its contents

**Comment by Hiallthejetbrains** [comment]
`-Xms256m
-Xmx1g
-XX:ReservedCodeCacheSize=512m
-XX:+IgnoreUnrecognizedVMOptions
-XX:+UseG1GC
-XX:SoftRefLRUPolicyMSPerMB=50
-XX:CICompilerCount=2
-XX:+HeapDumpOnOutOfMemoryError
-XX:-OmitStackTraceInFastThrow
-ea
-Dsun.io.useCanonCaches=false
-Djdk.http.auth.tunneling.disabledSchemes=""
-Djdk.attach.allowAttachSelf=true
-Djdk.module.illegalAccess.silent=true
-Dkotlinx.coroutines.debug=off
-XX:ErrorFile=$USER_HOME/java_error_in_idea_%p.log
-XX:HeapDumpPath=$USER_HOME/java_error_in_idea.hprof

--add-opens=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED
--add-opens=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED

`

**Comment by novice88** [comment]
![image](https://github.com/novice88/jetbra/assets/76272583/b8e51bf0-5197-4e05-b0b5-ccf1a7ecff73)

There's no such line?

**Comment by Hiallthejetbrains** [comment]
Nope.

**Comment by novice88** [comment]
This is really strange, normally if you run the installer script, the installer script will write this line in the file

**Comment by Hiallthejetbrains** [comment]
When I run the installer.sh with bash on MacOS, I get the error `jetbra-agent.jar not found`

**Comment by novice88** [comment]
Please show the directory structure of the jetbra-all.zip you downloaded after unzipping it

**Comment by Hiallthejetbrains** [comment]
<img width="638" alt="Screenshot" src="https://github.com/novice88/jetbra/assets/157857426/254034e6-dd07-470e-a7f9-3889c1100530">

**Comment by novice88** [comment]
![image](https://github.com/novice88/jetbra/assets/76272583/bd280d02-93f4-4cc8-9a35-d311712e86e8)
You downloaded the source code.

**Comment by Hiallthejetbrains** [comment]
Oh woops. I knew it would be some dumb error on my end. Thanks! Also, from what I have heard, I am really excited to try it!
